// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateNote implements create-note operation.
//
// メモを作成する.
//
// POST /notes
func (UnimplementedHandler) CreateNote(ctx context.Context, req *ModelsNote) (r *ModelsNote, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUser implements create-user operation.
//
// ユーザーを作成する.
//
// POST /users
func (UnimplementedHandler) CreateUser(ctx context.Context, req *ModelsUser) (r *ModelsUser, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteNote implements delete-note operation.
//
// メモを削除する.
//
// DELETE /notes/{id}
func (UnimplementedHandler) DeleteNote(ctx context.Context, params DeleteNoteParams) (r DeleteNoteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteUser implements delete-user operation.
//
// ユーザーを削除する.
//
// DELETE /users/{id}
func (UnimplementedHandler) DeleteUser(ctx context.Context, params DeleteUserParams) (r DeleteUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNote implements get-note operation.
//
// メモを取得する.
//
// GET /notes/{id}
func (UnimplementedHandler) GetNote(ctx context.Context, params GetNoteParams) (r GetNoteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUser implements get-user operation.
//
// ユーザーを取得する.
//
// GET /users/{id}
func (UnimplementedHandler) GetUser(ctx context.Context, params GetUserParams) (r GetUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthCheckGetHealthCheck implements HealthCheck_getHealthCheck operation.
//
// Returns the health status of the API.
//
// GET /healthcheck
func (UnimplementedHandler) HealthCheckGetHealthCheck(ctx context.Context) (r *RoutesHealthCheckResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListNotes implements list-notes operation.
//
// メモ一覧を取得する.
//
// GET /notes
func (UnimplementedHandler) ListNotes(ctx context.Context) (r []ModelsNote, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUsers implements list-users operation.
//
// ユーザー一覧を取得する.
//
// GET /users
func (UnimplementedHandler) ListUsers(ctx context.Context) (r []ModelsUser, _ error) {
	return r, ht.ErrNotImplemented
}
