// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateNoteOperation                OperationName = "CreateNote"
	CreateUserOperation                OperationName = "CreateUser"
	DeleteNoteOperation                OperationName = "DeleteNote"
	DeleteUserOperation                OperationName = "DeleteUser"
	GetNoteOperation                   OperationName = "GetNote"
	GetUserOperation                   OperationName = "GetUser"
	HealthCheckGetHealthCheckOperation OperationName = "HealthCheckGetHealthCheck"
	ListNotesOperation                 OperationName = "ListNotes"
	ListUsersOperation                 OperationName = "ListUsers"
)
