// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateNoteOperation OperationName = "CreateNote"
	DeleteNoteOperation OperationName = "DeleteNote"
	GetNoteOperation    OperationName = "GetNote"
	ListNotesOperation  OperationName = "ListNotes"
)
