// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateNote implements create-note operation.
	//
	// メモを作成する.
	//
	// POST /notes
	CreateNote(ctx context.Context, req *ModelsNote) (*ModelsNote, error)
	// DeleteNote implements delete-note operation.
	//
	// メモを削除する.
	//
	// DELETE /notes/{id}
	DeleteNote(ctx context.Context, params DeleteNoteParams) (DeleteNoteRes, error)
	// GetNote implements get-note operation.
	//
	// メモを取得する.
	//
	// GET /notes/{id}
	GetNote(ctx context.Context, params GetNoteParams) (GetNoteRes, error)
	// ListNotes implements list-notes operation.
	//
	// メモ一覧を取得する.
	//
	// GET /notes
	ListNotes(ctx context.Context) ([]ModelsNote, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
