// Code generated by ogen, DO NOT EDIT.

package ogen

// DeleteNoteNoContent is response for DeleteNote operation.
type DeleteNoteNoContent struct{}

func (*DeleteNoteNoContent) deleteNoteRes() {}

// DeleteNoteNotFound is response for DeleteNote operation.
type DeleteNoteNotFound struct{}

func (*DeleteNoteNotFound) deleteNoteRes() {}

// GetNoteNotFound is response for GetNote operation.
type GetNoteNotFound struct{}

func (*GetNoteNotFound) getNoteRes() {}

// Ref: #/components/schemas/Models.Note
type ModelsNote struct {
	ID      int64  `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

// GetID returns the value of ID.
func (s *ModelsNote) GetID() int64 {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *ModelsNote) GetTitle() string {
	return s.Title
}

// GetContent returns the value of Content.
func (s *ModelsNote) GetContent() string {
	return s.Content
}

// SetID sets the value of ID.
func (s *ModelsNote) SetID(val int64) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *ModelsNote) SetTitle(val string) {
	s.Title = val
}

// SetContent sets the value of Content.
func (s *ModelsNote) SetContent(val string) {
	s.Content = val
}

func (*ModelsNote) getNoteRes() {}
