// Code generated by ogen, DO NOT EDIT.
package ogen

type DeleteNoteRes interface {
	deleteNoteRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type GetNoteRes interface {
	getNoteRes()
}

type GetUserRes interface {
	getUserRes()
}
