// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateNote implements create-note operation.
//
// メモを作成する.
//
// POST /notes
func (UnimplementedHandler) CreateNote(ctx context.Context, req *ModelsNote) (r *ModelsNote, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNote implements get-note operation.
//
// メモを取得する.
//
// GET /notes/{id}
func (UnimplementedHandler) GetNote(ctx context.Context, params GetNoteParams) (r *ModelsNote, _ error) {
	return r, ht.ErrNotImplemented
}
